[package]
name = "aw3d30-parquet"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3"
gdal = "0.9"
parquet = "5"
rusoto_core = "0.47"
rusoto_s3 = "0.47"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
