name: Assets

on:
  release:
    types:
    - created

jobs:
  darwin:
    name: Darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GDAL
      run: brew install gdal
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Create archive
      run: tar -C target/release -czf aw3d30-parquet-${{ github.event.release.tag_name }}-x86_64-apple-darwin.tar.gz aw3d30-parquet
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: aw3d30-parquet-${{ github.event.release.tag_name }}-x86_64-apple-darwin.tar.gz
        asset_name: aw3d30-parquet-${{ github.event.release.tag_name }}-x86_64-apple-darwin.tar.gz
        asset_content_type: application/gzip

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - name: Install GDAL
      run: sudo apt-get install -y libgdal-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      env:
        GDAL_STATIC:
      with:
        command: build
        args: --release
    - name: Create archive
      working-directory: ./target/release
      run: tar -czf ../../aw3d30-parquet-${{ github.event.release.tag_name }}-${{ matrix.target }}.tar.gz aw3d30-parquet
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: aw3d30-parquet-${{ github.event.release.tag_name }}-${{ matrix.target }}.tar.gz
        asset_name: aw3d30-parquet-${{ github.event.release.tag_name }}-${{ matrix.target }}.tar.gz
        asset_content_type: application/gzip
